#! /usr/bin/bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# --- Auto start ---
xsetroot -solid '#5A8E3A'
lxsession &
nitrogen --restore &
picom &

# remove all existing keybindings
hc keyunbind --all

# --- Variables ---
# Mod=Mod4  # Use super as modkey
Mod=Mod1    # Use alt as modkey
Term=st
Editor="nvim"
Panel=dzen2

resizeStep=0.02
volumeStep=2
brightnessStep=5
gapStep=2

# --- Keybindings ---
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn $Term
hc keybind $Mod-m spawn dmenu_run
hc keybind $Mod-n spawn $Term -g 133x33 -t Notes -e $HOME/Documents/notes/notetaker

# Volume controls
# Computer volume
hc keybind $Mod-F1 spawn amixer set Master toggle
hc keybind $Mod-F2 spawn amixer set Master $volumeStep%- unmute
hc keybind $Mod-F3 spawn amixer set Master $volumeStep%+ unmute
hc keybind $Mod-F4 spawn amixer set Capture toggle
# cmus volume
hc keybind $Mod-Shift-F2 spawn cmus-remote -v -$volumeStep%
hc keybind $Mod-Shift-F3 spawn cmus-remote -v +$volumeStep%
hc keybind $Mod-F9  spawn cmus-remote -r
hc keybind $Mod-F10 spawn cmus-remote -u
hc keybind $Mod-F11 spawn cmus-remote -s
hc keybind $Mod-F12 spawn cmus-remote -n

# Brightness controls
hc keybind $Mod-F5 spawn xbacklight -$brightnessStep%
hc keybind $Mod-F6 spawn xbacklight +$brightnessStep%

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Mod4-h     shift left
hc keybind $Mod-Mod4-j     shift down
hc keybind $Mod-Mod4-k     shift up
hc keybind $Mod-Mod4-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-Shift-h split left   0.5
hc keybind $Mod-Shift-j split bottom 0.5
hc keybind $Mod-Shift-k split top    0.5
hc keybind $Mod-Shift-l split right  0.5

# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
hc keybind $Mod-Control-h       resize left +$resizeStep
hc keybind $Mod-Control-j       resize down +$resizeStep
hc keybind $Mod-Control-k       resize up +$resizeStep
hc keybind $Mod-Control-l       resize right +$resizeStep

# Increase or decrease frame gap
hc keybind $Mod-equal spawn $HOME/.config/herbstluftwm/frameGaps.sh $gapStep
hc keybind $Mod-minus spawn $HOME/.config/herbstluftwm/frameGaps.sh -$gapStep
hc keybind $Mod-0 set frame_gap 0

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Mod4-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-s set_attr clients.focus.floating toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

hc keybind $Mod-= mirror both

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-backslash   cycle_monitor
hc keybind $Mod-Tab         cycle +1
hc keybind $Mod-Shift-Tab   cycle -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
# hc set frame_bg_active_color '#345F0C'
hc set frame_bg_active_color '#003972'
hc set frame_border_width 1
hc set always_show_frame on
hc set frame_bg_transparent on
hc set frame_transparent_width 5
hc set frame_gap 0
hc set default_frame_layout max
hc substitute ALGO settings.default_frame_layout \
    foreach T tags.by-name. \
        sprintf ATTR '%c.tiling.root.algorithm' T \
        set_attr ATTR ALGO

hc attr theme.active.color '#008dbc'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 1

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule title='Notes' floating=on

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors
# hc set_monitors 1920x1080+0+0 1920x1060+1920+20

# Kill already running bar instances
killall -q $Panel

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" "$monitor" &
done
