#!/bin/bash
# Code adapted from https://www.youtube.com/watch?v=zB_3FIGRWRU

noteFilename="$HOME/Documents/notes/todos.md"

if [ ! -f $noteFilename ]; then
  touch $noteFilename
fi

nvim -c "norm G" \
  -c "norm zz" \
  $noteFilename
