#!/bin/sh
# Code stolen from https://www.youtube.com/watch?v=zB_3FIGRWRU

noteFilename="$HOME/Documents/notes/note-$(date +%Y-%m-%d).md"

if [ ! -f $noteFilename ]; then
  echo "# --- $(date +%Y-%m-%d) ---" > $noteFilename
fi

nvim -c "norm Go" \
  -c "norm Go ## $(date +%H:%M)" \
  -c "norm G2o" \
  -c "norm zz" \
  -c "startinsert" $noteFilename
